Parameters:
  KeyName: #키페어 리전에 종속
    Description: Name of an exsting EC2 KeyPair to enable SSH access to the instances. Linked to AWS parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: My-VPC
      EnableDnsHostnames: true 	
  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: My-IGW
  MyPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: My-Public-RT
  MyDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MyIGWAttachment
    Properties:
      RouteTableId: !Ref MyPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyIGW
  MyPublicSNRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyPublicRT
      SubnetId: !Ref MyPublicSN
  # MyPublicSN1RouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref MyPublicRT
  #     SubnetId: !Ref MyPublicSN1
  MyIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyIGW
      VpcId: !Ref MyVPC
  MyPublicSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: My-Public-SN
  # MyPublicSN1:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     AvailabilityZone: !Select [ 2, !GetAZs '' ]
  #     CidrBlock: 10.0.1.0/24
  #     Tags:
  #       - Key: Name
  #         Value: My-Public-SN
  ServerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c76973fbe0ee100c
      # ami-03b42693dc6a7dc35 #리전에 종속
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Server-EC2
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref MyPublicSN
          GroupSet:
          - !Ref ServerSG
          AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.0.100
      # SourceDestCheck: false # 해당 옵션이 있어야 포워딩 가능
      # NetworkInterfaces:
      #   - NetworkInterfaceId: !Ref Instance1ENIEth0
      #     DeviceIndex: 0
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash
          hostnamectl --static set-hostname Seoul-IDC-DB
          yum install -y mariadb-server mariadb lynx
          systemctl start mariadb && systemctl enable mariadb
          echo -e "\n\nqwe123\nqwe123\ny\ny\ny\ny\n" | /usr/bin/mysql_secure_installation
          systemctl restart mariadb
          systemctl enable mariadb
  # ServerEC22:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.micro
  #     ImageId: ami-0c76973fbe0ee100c
  #     # ami-03b42693dc6a7dc35 #리전에 종속
  #     KeyName: !Ref KeyName
  #     Tags:
  #       - Key: Name
  #         Value: Server-EC2-2
  #     NetworkInterfaces:
  #       - DeviceIndex: 0
  #         SubnetId: !Ref MyPublicSN1
  #         GroupSet:
  #         - !Ref ServerSG
  #         AssociatePublicIpAddress: true
  #         PrivateIpAddress: 10.0.1.100
  #     # SourceDestCheck: false # 해당 옵션이 있어야 포워딩 가능
  #     # NetworkInterfaces:
  #     #   - NetworkInterfaceId: !Ref Instance1ENIEth0
  #     #     DeviceIndex: 0
  #     UserData:
  #       Fn::Base64:
  #         !Sub |
  #           #!/bin/bash
  #           hostname ELB-EC2-2
  #           yum install httpd -y
  #           yum install net-snmp net-snmp-utils -y
  #           yum install tcpdump -y
  #           service httpd start
  #           chkconfig httpd on
  #           service snmpd start
  #           chkconfig snmpd on
  #           echo "<h1>My-EC2 Web Server2</h1>" > /var/www/html/index.html  
  ServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Server-SG
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

  # ApplicationLoadBalancer:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     Name: My-ALB
  #     Scheme: internet-facing
  #     #Scheme: Internal
  #     SecurityGroups:
  #       - !Ref ServerSG
  #     Subnets:
  #       - !Ref MyPublicSN
  #       - !Ref MyPublicSN1
       
  # ALBListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - Type: forward
  #         TargetGroupArn: !Ref ALBTargetGroup
  #     LoadBalancerArn: !Ref ApplicationLoadBalancer
  #     Port: 80
  #     Protocol: HTTP
  # ALBTargetGroup:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     Name: My-ALB-TG
  #     Port: 80
  #     Protocol: HTTP
  #     VpcId: !Ref MyVPC
  #     #HealthCheckPath: /login.php
  #     Targets:
  #       - Id: !Ref ServerEC2
  #         Port: 80
  #       - Id: !Ref ServerEC22
  #         Port: 80
  # PublicDNS:
  #   Type: AWS::Route53::HostedZone
  #   Properties:
  #     Name: yonggi90.tk
  #     HostedZoneConfig:
  #       Comment: Public hosted zone for yonggi90.tk


  # PrimaryRecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     Name: test.yonggi90.tk
  #     Type: A
  #     TTL: 30
  #     HostedZoneId: !Ref PublicDNS
  #     ResourceRecords:
  #       - !GetAtt ServerEC2.PublicIp
 
